- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions >= 500"
- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions >= 200 & $additions <= 500"
- label: "PR Size"
  message: "Small"
  color: "green"
  when: "$additions > 200"
